version: "3"
services: 
  mysqldb: 
    container_name: mysqldb
    image: mysql:8.0
    ports: 
      - 3307:3306   
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize database with init.sql
      - ./dbfile/:/var/lib/mysql                        # Persist MySQL data outside the container
  springboot-app:
    container_name: springboot-app
    image: springbooot-app
    restart: always
    build: .
    ports:
      - 8081:8080 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  react-app:
    container_name: react-app
    image: react-app
    restart: always
    ports:
      - 8080:5173
    #volumes:
      #- ../Frontend/inventoryManagementSystem:/app
    #command: /bin/sh -c "npm install && npm run dev && mkdir -p node_modules && chmod -R 777 node_modules"
    environment:
      REACT_APP_API_BASE_URL: http://springboot-app:8080
    depends_on:
      - springboot-app
